// <auto-generated />
using System;
using Imi.Project.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Imi.Project.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221019143811_FixRecipeDescriptionColumnAttempt1")]
    partial class FixRecipeDescriptionColumnAttempt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Ingedrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Ingedrients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9824),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9826),
                            Name = "Melk",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9828),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9828),
                            Name = "Laurier",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9830),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9830),
                            Name = "Gehakt",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9832),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9832),
                            Name = "Tomatenpuree",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9834),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9834),
                            Name = "Boter",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9836),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9836),
                            Name = "Paprika",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9838),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9838),
                            Name = "Wortel",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9840),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9840),
                            Name = "Ajuin",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9842),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9843),
                            Name = "Kippenbouillon",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9844),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9845),
                            Name = "Olijfolie",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9846),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9847),
                            Name = "Champignons",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9848),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9849),
                            Name = "Gemalen kaas",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9850),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9851),
                            Name = "Spaghetti",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9852),
                            LastEditedOn = new DateTime(2022, 10, 19, 14, 38, 10, 707, DateTimeKind.Utc).AddTicks(9853),
                            Name = "Courgette",
                            UnitOfMeasureId = new Guid("00000000-0000-0000-0000-000000000011")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9876),
                            Description = "Dit recept test de werking van dit recept.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9915),
                            Title = "Testrecept"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9919),
                            Description = "Maak een roux van de boter en de bloem. Dit doe je door de boter in een steelpannetje te smelten. Doe de bloem bij de boter en roer met de garde.\r\n\r\nLaat het mengsel een beetje opdrogen in het pannetje, tot je de geur van koekjes ruikt.\r\n\r\nGiet er beetje bij beetje de koude melk bij en roer telkens het mengsel glad. Breng al roerend aan de kook, op matig vuur. Laat de witte saus indikken en laat nog enkele minuten doorkoken zodat de bloemsmaak verdwijnt.Breng op smaak met nootmuskaat, peper en zout.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9920),
                            Title = "Witte saus"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9924),
                            Description = "Koop brochetten van de slager, easy. Smijt ze in een ovenpan, doe er boter over en zet ze in de combi-oven. Serveer met rijst en wortelen.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9925),
                            Title = "Gemarineerde brochetten"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9929),
                            Description = "Neem een ruime mengschaal, doe er het warm water in en week er de gedroogde paddenstoelen in. Het eekhoorntjesbrood zal z’n smaak afgeven en het water in een bouillon veranderen. Pel de uien en snij ze in grove stukken. Verhit een ruime stoofpot of een soepketel. Smelt er een klont boter in en stoof de stukken ui. Snij de stammen prei overlangs door, snij het donkerste loof weg en spoel ze onder stromend water. Snij de gewassen prei in grove stukken en stoof ze mee met de uien. Pel de look, snij de teentjes grof en laat ze ook meestoven. Maak 2/3 van de Parijse paddenstoelen schoon. Gebruik een borsteltje en snij (indien nodig) het steeltje wat bij. Snij de paddenstoelen vervolgens middendoor en laat ze meestoven. Hou 1/3 van de paddenstoelen opzij. Maak een bouquet garni met enkele blaadjes laurier, wat tijm en (indien beschikbaar) peterseliestengels. Bind alles samen met een eindje keukentouw en laat het kruidentuiltje meestoven. Schil de aardappelen en snij ze in grove stukken. Laat ze meestoven. Zeef de bouillon van eekhoorntjesbrood en giet het vocht in de soepketel met gestoofde groenten. De rubberachtige gewelde paddenstoelen gebruiken we niet. Laat de soep een half uur sudderen op een zacht vuur. Intussen kan je de kaasstengels bereiden. Verwijder het bouquet garni en mix de soep glad met een staafmixer. Je hoeft ze niet te zeven. Mix er ook een flinke scheut room in. Proef de soep en kruid het gerecht naar smaak met wat peper van de molen en een snuif zout.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9930),
                            Title = "Champignonsoep"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9933),
                            Description = "Meng gehakt en ajuin in een schaal en mix ze. Smijt de mix in een ovenpan en herschaap het tot een brood. Doe er vervolgens paneermeel en boter over. 20 minuten in de combi-oven. Kook de patatten en de bonen. Smakelijk.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9935),
                            Title = "Gehaktbrood met bonen en patatten"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9938),
                            Description = "Wortelen snijden en koken. Kook de patatten. Doe de hamburger in een pan en laat het bakken. Easy-peasy.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9940),
                            Title = "Hamburger met wortel en patatten"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9943),
                            Description = "1-pansgerecht met viskroketjes en patatjes. Groenten zijn voor de dieren.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9945),
                            Title = "Viskroketjes met gebakken aardappelen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9948),
                            Description = "Patatten koken tot ze zacht zijn. Water afgieten, doe er melk en nootmuskaat bij. Grillworst in de microgolfoven voor anderhalf minuut ofzo.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9950),
                            Title = "Grillworst met puree"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9953),
                            Description = "1) Snij de ajuin, paprika, wortelen, courgette en champignons tot je ze klein genoeg vindt. Doe ze vervolgens allemaal in de pot met wat boter.2) Smijt het gehakt in een pan en bak ze lichtjes. Kap ze in kleinere stukken eenmaal de buitenkant gebakken is.3) Kook de spaghetti en voeg voldoende tomatenpuree en kruiden bij de bolognaise.4) Serveer met gemalen kaas.5) Bon appetit.",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9955),
                            Title = "Spaghetti bolognaise"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9958),
                            Description = "Ga naar de frituur ipv te koken. Ongelooflijk goed he LOL!",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9960),
                            Title = "Ongelooflijk goed gerecht"
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.RecipeIngedrient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngedrientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecipeId", "IngedrientId");

                    b.HasIndex("IngedrientId");

                    b.ToTable("RecipeIngedrients");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000004"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000006"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000007"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000008"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000008"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000008"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000009"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000010"),
                            IngedrientId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeasureUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            MeasureUnit = "gram"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            MeasureUnit = "liter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            MeasureUnit = "blik(ken)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            MeasureUnit = "tak(ken)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            MeasureUnit = "blaadje(s)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            MeasureUnit = "deciliter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            MeasureUnit = "centiliter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            MeasureUnit = "bakje(s)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            MeasureUnit = "vrij naar keuze"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            MeasureUnit = "geen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            MeasureUnit = " "
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9982),
                            Email = "admin@admin.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9984)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9987),
                            Email = "woutercallewaert@gmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9988)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9991),
                            Email = "jjameson@hotmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9993)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9996),
                            Email = "tigbiddies@xxx.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 707, DateTimeKind.Local).AddTicks(9998)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local),
                            Email = "allthebutz@hotmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(2)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(5),
                            Email = "ikloopindiestrond@gagmaker.net",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(7)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(9),
                            Email = "olklo@gmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(11)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(14),
                            Email = "wsmets1991@hotmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(15)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(18),
                            Email = "maarten.raviola@gmail.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(20)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(23),
                            Email = "toiletbril@lolbroek.com",
                            LastEditedOn = new DateTime(2022, 10, 19, 16, 38, 10, 708, DateTimeKind.Local).AddTicks(24)
                        });
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Ingedrient", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Recipe", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.RecipeIngedrient", b =>
                {
                    b.HasOne("Imi.Project.Api.Core.Entities.Ingedrient", "Ingedrient")
                        .WithMany("UsedInRecipes")
                        .HasForeignKey("IngedrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imi.Project.Api.Core.Entities.Recipe", "Recipe")
                        .WithMany("ListOfIngedrients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingedrient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Ingedrient", b =>
                {
                    b.Navigation("UsedInRecipes");
                });

            modelBuilder.Entity("Imi.Project.Api.Core.Entities.Recipe", b =>
                {
                    b.Navigation("ListOfIngedrients");
                });
#pragma warning restore 612, 618
        }
    }
}
